#!/usr/bin/env bash
# Script that display information about subdomains

display_dns_info() {
    local domain=$1
    local subdomain=$2

    local result=$(dig +noall +answer $subdomain.$domain | awk 'NR==1 {print $4, $5}')
    if [[ -n "$result" ]]; then
        local record_type=$(echo $result | awk '{print $1}')
        local destination=$(echo $result | awk '{print $2}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        echo "No DNS record found for $subdomain.$domain"
    fi  
}

if [[ "$#" -lt 1 ]]; then
    echo "Usage: $0 <domaine> [subdomain]"
    exit 1
fi

domain=$1
subdomain=$2

if [[ -n $subdomain ]]; then
    display_dns_info $domain $subdomain
else
    declare -a subdomains=("www" "lb-01" "web-01" "web-02")
    for sd in "${subdomains[@]}"; do
        display_dns_info $domain $sd
    done
fi 
