#!/usr/bin/env bash
# HAproxy installation and configuration
STUDENT_ID="484998"
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 $STUDENT_ID-web-01:80 check
    server web-02 $STUDENT_ID-web-02:80 check
EOT

sudo systemctl enable haproxy
sudo systemctl start haproxy
sudo systemctl status haproxy
