#!/usr/bin/env bash
# fixe the issue for listning on port 80

sudo apt update
sudo apt install -y net-tools
sudo apt install -y nginx
sudo netstat -tuln | grep ':(80|443)'
sudo systemctl enable nginx
sudo nginx
