#!/usr/bin/env bash
#script that displays Best School 10 times, displays Best School and then Hi on a new line on 9th line
i=1
while ((i <= 10)); do
    echo "Best School"
    if ((i==9))
    then
        echo "Hi"
    fi
    ((i++))
done
