#!/usr/bin/env bash
#scripts that loops over 10 iterations: 4 bad luck, 8 good luck, else Best school
i=1
while ((i <= 10)); do
    if ((i==4))
    then
        echo "bad luck"
    elif ((i==8))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
