#!/usr/bin/env bash
#let server run nginx user and listen on port 8080
sudo chmod 644 /etc/nginx/nginx.cong
if ! grep -q "^user nginx;" /etc/nginx/nginx.conf; then
   sed -i '1iuser nginx;' /etc/nginx/nginx.conf
fi
echo "listen 8080;" | sudo tee -a /etc/nginx/sites-available/default > /dev/null
echo "listen [::]:8080;" | sudo tee -a /etc/nginx/sites-available/default > /dev/null
sudo netstat -tulnlp | grep 8080
pgrep apache2
sudo pkill apache2
sudo service nginx restart
sudo nginx -s reload
